CREATE TABLE RECORD (
   id DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   acdval FLOAT NOT NULL,
   trbval FLOAT NOT NULL,
   tmpcelval FLOAT NOT NULL,
   tmpfarval FLOAT NOT NULL,
   PRIMARY KEY (id)
);
