CREATE TABLE `RECORD` (
   id DATETIME PRIMARY KEY DEFAULT NOW()
);

CREATE TABLE `ACIDITY` (
   id DATETIME PRIMARY KEY,
   record_id DATETIME,
   voltage FLOAT NOT NULL,
   value FLOAT NOT NULL,
   reading VARCHAR(25) NOT NULL,
   FOREIGN KEY (record_id) REFERENCES RECORD(id)
);

CREATE TABLE `TURBIDITY` (
   id DATETIME PRIMARY KEY,
   record_id DATETIME,
   voltage FLOAT NOT NULL,
   value FLOAT NOT NULL,
   reading VARCHAR(25) NOT NULL,
   FOREIGN KEY (record_id) REFERENCES RECORD(id)
);

CREATE TABLE `TEMPERATURE` (
   id DATETIME PRIMARY KEY,
   record_id DATETIME,
   voltage FLOAT NOT NULL,
   value FLOAT NOT NULL,
   reading VARCHAR(25) NOT NULL,
   FOREIGN KEY (record_id) REFERENCES RECORD(id)
);